### PR TITLE
Django 4.0 and Wagtail 2.16 Upgrade

### PR DESCRIPTION
**Pull request by FlipperPA**
This PR builds on the work of @rgs258 to upgrade both Wagtail to 2.16 and Django to 4.x.

### CODE REVIEW

**Comment by FlipperPA** [comment]
This completes the upgrade to Django 4.0 and Wagtail 2.16:

- Test suite has been updated to only include supported versions of Python, Django, and Wagtail
- Radio button and checkboxes have been changed to `<div>` from `<ul>` / `<li>`
- `DeleteView` now uses `form_valid()` for customizations rather than `delete()`
- `django.conf.urls` is now removed; must use `django.urls`
- `ugettext*` has been removed: must use `gettext*`
- `DEFAULT_AUTO_FIELD` added to test settings
- Wagtail 2.11 specific tests removed, as it is no longer a supported version

This should buy us a few years of compatibility before any more deprecations bite us. Thanks for creating such a fantastic package!

**Comment by leongraumans** [comment]
Hi, we've updated the tox tests with the following:

* Dropped Django 2.X 3.0 and 3.1 support
* Dropped Python 3.6 support
* Dropped Wagtail 2.2 > 2.14 support

see: https://github.com/labd/wagtailstreamforms/releases/tag/3.18.1

Could you update your PR?

**Comment by FlipperPA** [comment]
@leongraumans Thanks so much for taking a look - I've fixed the merge conflicts and pushed.

**Comment by leongraumans** [comment]
@FlipperPA nice, I've created a release ==> 3.19.0

**Comment by FlipperPA** [comment]
@leongraumans @rgs258 Thank you very much - we very much appreciate this. Let us know if you ever want help with some co-maintainers from Wharton. I believe we have some friends in common in the Wagtail Slack channel. 💯

**Pull request merged**
